#!/bin/sh
# this script deletes any stale lockfiles (often generated by XQuartz crashes)
# their existence causes the x11 display number to increate with each crash
set -e

clear_xquarts_locks() {
  for lockfile in /tmp/.X*-lock; do
    lockpid=$(cat "$lockfile")

    # shellcheck disable=SC2009
    if ! ps -p "$lockpid" | grep -qF "XQuartz.app"; then
      rm -vf -- "$lockfile"
    fi
  done
}

main() {
  clear_xquarts_locks
}

[ -n "$IMPORT" ] || main "$@"
